language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
script: python -m pytest
deploy:
  provider: pypi
  user: "josephmancuso"
  password:
    secure: "Iwnr8WZHI/o3H0OMIHfaG8Pz+8DVB92EWBNTn4RpDyeyqUcm6f1vqoxVgy2qFWVk1Nzg1KpCeKTHYTa2Sz2dISzxEa/GglKmawG0rcAjiEymdjEvnno7No0/pDm5pbzWlRBwfI5zXf0tKaFw3+duCqMCQ/EReSrq7C/Zidv7LO8qmb6yk6T9G17v9EXgR2DXAk3U5HjLv8gD9FR8Z2GGJ8WJSUJgk4pOnUr5a+UaQacGQSP3ARAzJn6cM+oBB6OeuI2Z24MX5M0xGVJ3U/5VPKnLhYh6GTcFYmjPxNLiY0+y7bdoXfhEHUAQTg762X81p6GoW15tRwjN54z6UypwTl/5ao1WnOkmqe1LTRw2ZZnPE3Azh528OSU84psIJX8OAnd7v4iLnh8OrZ7J/m7C2NezK19xtWVUCiYBFD3GlJX1cFLpucuv6TkH9JHiaA02NWJPBZLB4abODN8fw1Id6Y+lEDgBuHVvxOENsPlUxZJtGuf3l6873MIlj57d7YAHXm6Q3Sreqh6OIHR3PM8eLS3aqSD4Gd71kX8KHcYAol7j9Ooj5AEtE5otkEhp3Um4l7++zRxARiqYgON0KfiyPnMWgcY+KVy2SqmH6wDga+ZJQUMJ0dj+TErfxa/cXw+PJ2t368h9x+nsLl3uADnPYe9pQECjDQy7pzVKkPyD7q4="
  on:
    tags: true
