language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
script: python -m pytest
deploy:
  provider: pypi
  user: "josephmancuso"
  password:
    secure: "KE1NhLq7CVgtC1GKRggYCyi6yYJU09BXa9l/RUvszFwsqe1b/TGXDM0n9nAwhrz6AB/IDmh8QCTYY7bGLUod3tbAtQluWbJm56xn1C5jV46GWztvTAtP/+kzadyb/Gx6ZmwzC8Yiy0rMcvMJBKKdOScdclrxcW4lsVNmu0I18HNk6hgGfylhLzAl++KEREyfCNNDfYc67zcKtorACVbRavO/r9FVVQTSHt7rmpNOSQk4kEFe8WYylBWB3PqrQrrHWJb1ASMoxLXN8AP/OLFust01xDZZvrBe8VM/D5NcMRhAQ7q0j2N+Rx3E/nui/Em5ngQ3sK2JIkhMPejXGyHyot2dFF15qs9MpPtg5o1HLwWdeQ/EeYW4lJ9yrd5xFKYEviNDWTExwO1b3qLKqoAZ1c8QoRHd6xjYA/k83JSf5jEgRpOzY4C6Gtn3U1UMz67UDfeZPaLaGZmsQBm9j0wy9wwltMtczJEWh9wPWPCJ7nGpwz8UnPIhE1zSA86BZnaw0xu6Vu+yk1UFYfdUuAYQ5ttcdZIglYdxvGa6nfEeV2VNnCwRbthf34p7oaQ2NZn8i2sFU82mLMXTaZ9aR2deqbopjknTUgmaznO/rb1ZempvSXf2l8Vih6nVepFLabvmVAoSe2lYarmVZIjauH0VK0zxw9qcnKGXfMtRq2ImcdM="  
  on:
    tags: true
